version: '3.8'

services:
    nginx:
        build: 
            context: .
            dockerfile: nginx.dockerfile
        ports:
            - 8000:80
        volumes:
            - ./src:/var/www/html
        depends_on:
            - mysql
            - php
        links:
            - php:waapi_php_1
    mysql:
        image: mysql:5.7
        ports:
            - 3308:3306
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - ./mysql:/var/lib/mysql
    php:
        container_name: waapi_php_1
        build:
            context: .
            dockerfile: php.dockerfile
        volumes:
            - ./src:/var/www/html
    composer:
        build:
            context: .
            dockerfile: composer.dockerfile
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html