version: '3.8'

services:
    nginx:
        container_name: nginx
        build: 
            context: .
            dockerfile: nginx.dockerfile
        ports:
            - 80:80
        volumes:
            - ./src:/var/www/html
        depends_on:
            - mysql
            - php
        links:
            - php:php8012
    mysql:
        container_name: mysql57
        image: mysql:5.7
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - ./mysql:/var/lib/mysql
    php:
        container_name: php8012
        build:
            context: .
            dockerfile: php.dockerfile
        volumes:
            - ./src:/var/www/html
    composer:
        container_name: composer
        build:
            context: .
            dockerfile: composer.dockerfile
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html